#include "gui_mediamtx.h"

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ---- config rendering ---------------------------------------------------- */

gui_mediamtx_config_t gui_mediamtx_default_config(void)
{
    /* mediamtx canonical + 100 across every listener, so the whole set follows
     * one rule. capture-node's scheme is tier x 10000 + its own canonical base,
     * which cannot reach any of these at any tier. */
    gui_mediamtx_config_t cfg = {
        .lan         = false,
        .rtsp        = 8654,
        .rtp         = 8100,
        .rtcp        = 8101,
        .hls         = 8988,
        .webrtc_http = 8989,
        .webrtc_ice  = 8289,
        .metrics     = 10098,
    };
    return cfg;
}

typedef struct {
    char  *out;
    size_t cap;
    size_t len;
    bool   overflow;
} yaml_buf_t;

static void yb_addf(yaml_buf_t *b, const char *fmt, ...)
{
    if (b->overflow) {
        return;
    }
    va_list ap;
    va_start(ap, fmt);
    int n = vsnprintf(b->out + b->len, b->cap - b->len, fmt, ap);
    va_end(ap);
    if (n < 0 || (size_t)n >= b->cap - b->len) {
        b->overflow = true;
        return;
    }
    b->len += (size_t)n;
}

/* Every reader costs bandwidth and CPU on the machine whose RF ingest we go out
 * of our way to protect with nice(+5), so the stream does not get to be an
 * unbounded fan-out. Far above any realistic number of people watching one tape
 * conversion, far below anything that could starve capture. Deliberately not a
 * setting: mediamtx reads 0 as "no limit", so an exposed value is a way for this
 * cap to be switched off by accident. */
#define MTX_MAX_READERS 8

int gui_mediamtx_render_config(const gui_mediamtx_config_t *cfg, char *out, size_t cap)
{
    if (cfg == NULL || out == NULL || cap == 0) {
        return -1;
    }

    /* Loopback pins the host; LAN leaves it off so mediamtx binds every
     * interface. Note there is no auth either way -- see the header. */
    const char *host = cfg->lan ? "" : "127.0.0.1";

    yaml_buf_t b = { out, cap, 0, false };

    yb_addf(&b,
        "# Generated by MISRC GUI - do not edit; rewritten on every launch.\n"
        "#\n"
        "# Ports are mediamtx canonical + 100, chosen so they cannot collide with\n"
        "# capture-node's instances on this host at any tier. Every listener we do\n"
        "# not serve is explicitly off: mediamtx defaults rtmp/srt/moq to yes, and\n"
        "# claiming those ports would take them from a service we do not own.\n"
        "\n");

    yb_addf(&b, "rtsp: yes\n");
    yb_addf(&b, "rtspAddress: %s:%u\n", host, (unsigned)cfg->rtsp);
    yb_addf(&b, "rtpAddress: %s:%u\n", host, (unsigned)cfg->rtp);
    yb_addf(&b, "rtcpAddress: %s:%u\n", host, (unsigned)cfg->rtcp);
    /* Excludes udpMulticast, which mediamtx enables by default and which would
     * bind two more UDP ports we never asked for. */
    yb_addf(&b, "rtspTransports: [udp, tcp]\n");
    /* Keeps RTSPS off, so nothing binds the encrypted RTSP port. */
    yb_addf(&b, "rtspEncryption: \"no\"\n\n");

    yb_addf(&b, "hls: yes\n");
    yb_addf(&b, "hlsAddress: %s:%u\n", host, (unsigned)cfg->hls);
    yb_addf(&b, "hlsVariant: lowLatency\n");
    yb_addf(&b, "hlsAlwaysRemux: no\n\n");

    yb_addf(&b, "webrtc: yes\n");
    yb_addf(&b, "webrtcAddress: %s:%u\n", host, (unsigned)cfg->webrtc_http);
    yb_addf(&b, "webrtcLocalUDPAddress: %s:%u\n", host, (unsigned)cfg->webrtc_ice);
    if (cfg->lan) {
        /* Remote browsers need a reachable ICE candidate. */
        yb_addf(&b, "webrtcIPsFromInterfaces: yes\n\n");
    } else {
        /* Advertising every LAN address for a server nothing off-box can reach
         * only gives browsers candidates that cannot work. */
        yb_addf(&b, "webrtcIPsFromInterfaces: no\n");
        yb_addf(&b, "webrtcAdditionalHosts: [127.0.0.1]\n\n");
    }

    yb_addf(&b,
        "readTimeout: 10s\n"
        "writeTimeout: 10s\n"
        "writeQueueSize: 512\n"
        "\n"
        "rtmp: no\n"
        "srt: no\n"
        "moq: no\n"
        "\n"
        "# These four default to no. So did rtmp/srt/moq -- except those default to\n"
        "# YES, which is the whole reason this file is generated rather than assumed.\n"
        "# A default is not a guarantee, and pprof reachable on a LAN interface\n"
        "# would be a genuine leak, so they are stated.\n"
        "api: no\n"
        "pprof: no\n"
        "playback: no\n"
        "\n");

    /* Metrics is the one admin endpoint we do serve, because it is the only
     * place the real published bitrate exists: ffmpeg's RTSP muxer reports
     * total_size and bitrate as N/A, and the kernel's per-process io counters
     * do not see socket writes. Both were measured before landing here.
     *
     * Bound to 127.0.0.1 unconditionally -- note this does NOT use `host` --
     * so that turning on LAN mode exposes the stream and nothing else. */
    yb_addf(&b, "metrics: yes\n");
    yb_addf(&b, "metricsAddress: 127.0.0.1:%u\n\n", (unsigned)cfg->metrics);

    /* Who may do what.
     *
     * Without this block mediamtx applies its shipped default -- `user: any`
     * with publish, read AND playback on every path. In LAN mode that let any
     * machine on the network publish to misrc-preview and, with
     * overridePublisher on, displace our ffmpeg: the operator monitoring a
     * customer's tape would have been shown someone else's video.
     *
     * Publishing is pinned to loopback in BOTH bind modes. Our publisher always
     * connects to rtsp://127.0.0.1 whatever the bind mode (gui_rtsp_stream.c),
     * so this costs nothing and needs no credential -- which matters, because a
     * credential in ffmpeg's argv would be readable from /proc/<pid>/cmdline by
     * any local user, and would land in its stderr log besides.
     *
     * Reading stays open: passwordless is the documented default, and LAN mode
     * exists precisely so that people can watch. */
    yb_addf(&b,
        "authInternalUsers:\n"
        "  # Our own ffmpeg. Nothing off-box may publish, credential or not.\n"
        "  - user: any\n"
        "    pass:\n"
        /* Quoted deliberately: ::1 is not a valid plain scalar inside a YAML
         * flow sequence, and the unquoted form makes the entire file fail to
         * parse -- mediamtx would refuse to start rather than misbehave, but
         * the stream would simply never come up. mediamtx quotes these in its
         * own shipped config for the same reason. */
        "    ips: [\"127.0.0.1\", \"::1\"]\n"
        "    permissions:\n"
        "      - action: publish\n"
        "        path: misrc-preview\n"
        "  # Viewers, from anywhere the bind mode allows.\n");
    if (cfg->read_password[0]) {
        /* Quoted: the alphabet is alphanumeric and safe unquoted, but a password
         * is exactly the sort of value that should not depend on that staying
         * true. VLC and browsers both prompt for these. */
        yb_addf(&b,
            "  - user: viewer\n"
            "    pass: \"%s\"\n", cfg->read_password);
    } else {
        yb_addf(&b,
            "  - user: any\n"
            "    pass:\n");
    }
    yb_addf(&b,
        "    ips: []\n"
        "    permissions:\n"
        "      - action: read\n"
        "        path: misrc-preview\n"
        "  # Us, reading the bitrate back off the metrics endpoint. Without this\n"
        "  # entry mediamtx answers /metrics with 401 -- which is the auth block\n"
        "  # above doing its job.\n"
        "  - user: any\n"
        "    pass:\n"
        "    ips: [\"127.0.0.1\", \"::1\"]\n"
        "    permissions:\n"
        "      - action: metrics\n"
        "\n");

    /* Deliberately outside capture-node's naming, so the two are never
     * confusable in a viewer's bookmarks. */
    yb_addf(&b,
        "paths:\n"
        "  misrc-preview:\n"
        "    source: publisher\n"
        "    sourceOnDemand: no\n"
        "    # Nothing takes this path out from under the publisher that owns it,\n"
        "    # not even from loopback.\n"
        "    overridePublisher: no\n");
    yb_addf(&b, "    maxReaders: %d\n", MTX_MAX_READERS);

    if (b.overflow) {
        /* Never hand back a truncated config: mediamtx would start on its own
         * defaults, with every listener we meant to disable. */
        out[0] = '\0';
        return -1;
    }
    return (int)b.len;
}


/* ---- process lifecycle --------------------------------------------------- */

#if defined(_WIN32)

void gui_mediamtx_set_binary_path(const char *path) { (void)path; }
bool gui_mediamtx_probe(void) { return false; }
const char *gui_mediamtx_binary_path(void) { return ""; }
const char *gui_mediamtx_version(void) { return ""; }
int gui_mediamtx_start(const gui_mediamtx_config_t *cfg, char *err, size_t err_cap)
{
    (void)cfg;
    if (err && err_cap) snprintf(err, err_cap, "mediamtx supervision requires a POSIX host");
    return -1;
}
void gui_mediamtx_stop(void) { }
void gui_mediamtx_shutdown(void) { }
void gui_mediamtx_poll(void) { }
uint32_t gui_mediamtx_stream_kbps(void) { return 0; }
const char *gui_mediamtx_read_password(void) { return ""; }
gui_mediamtx_status_t gui_mediamtx_get_status(void)
{
    gui_mediamtx_status_t st = {0};
    return st;
}
bool gui_mediamtx_is_running(void) { return false; }
int gui_mediamtx_test_main(int seconds)
{
    (void)seconds;
    fprintf(stderr, "requires a POSIX host\n");
    return 2;
}

#else

#include <errno.h>
#include <fcntl.h>
#include <netinet/in.h>
#include <signal.h>
#include <spawn.h>
#include <sys/resource.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

extern char **environ;

#define MTX_TERM_GRACE_S  3.0
#define MTX_KILL_GRACE_S  2.0
#define MTX_CHILD_NICE    5

static struct {
    int  child_pid;
    bool running;
    char config_path[512];
    char err_text[192];
    /* When the just-spawned child should be checked for an immediate exit. 0
     * once it has been checked. See gui_mediamtx_start(). */
    double verify_at;
    uint16_t metrics_port;
    char read_password[40];   /* what the RUNNING server is enforcing */
} mtx;

/* Reading the bitrate back out of mediamtx.
 *
 * Deliberately a state machine driven by poll() rather than a blocking fetch:
 * this runs on the render thread, and a mediamtx that has wedged must cost a
 * dropped sample, not a frozen window. That lesson is already paid for -- see
 * the non-blocking start path.  */
#define MTX_METRICS_PERIOD_S  2.0
#define MTX_METRICS_TIMEOUT_S 1.0

typedef enum { MET_IDLE = 0, MET_CONNECTING, MET_SENDING, MET_READING } met_phase_t;

static struct {
    int         fd;            /* -1 when idle */
    met_phase_t phase;
    double      started_at;    /* of the in-flight request */
    double      next_at;       /* when to start the next one */
    char        req[160];
    size_t      req_len, req_sent;
    char        buf[16384];
    size_t      len;

    uint64_t    last_bytes;
    double      last_at;       /* 0 = no previous sample */
    uint32_t    kbps;
} met = { .fd = -1 };

static struct {
    bool probed;
    bool found;
    char path[512];
    char version[80];
} mtx_bin;

static char s_mediamtx_override[512];

static double mtx_now(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (double)ts.tv_sec + (double)ts.tv_nsec / 1e9;
}

static void mtx_sleep(double seconds)
{
    struct timespec ts = { (time_t)seconds, (long)((seconds - (double)(time_t)seconds) * 1e9) };
    nanosleep(&ts, NULL);
}

static bool mtx_is_executable(const char *p)
{
    return p && p[0] && access(p, X_OK) == 0;
}

static bool mtx_find_in_path(char *out, size_t cap)
{
    const char *path = getenv("PATH");
    if (!path || !path[0]) return false;
    const char *p = path;
    while (*p) {
        const char *sep = strchr(p, ':');
        size_t len = sep ? (size_t)(sep - p) : strlen(p);
        if (len > 0 && len < cap - 16) {
            char cand[512];
            snprintf(cand, sizeof(cand), "%.*s/mediamtx", (int)len, p);
            if (mtx_is_executable(cand)) { snprintf(out, cap, "%s", cand); return true; }
        }
        if (!sep) break;
        p = sep + 1;
    }
    return false;
}

/* Next to our own binary. Unlike the ffmpeg resolver this is tried BEFORE
 * PATH: inside an AppImage the bundled mediamtx is the one we shipped and
 * tested against, and it should win over whatever the host happens to have. */
static bool mtx_find_beside_self(char *out, size_t cap)
{
    char selfdir[512];
    ssize_t n = readlink("/proc/self/exe", selfdir, sizeof(selfdir) - 1);
    if (n <= 0) return false;
    selfdir[n] = '\0';
    char *slash = strrchr(selfdir, '/');
    if (!slash) return false;
    *slash = '\0';
    char cand[600];
    snprintf(cand, sizeof(cand), "%s/mediamtx", selfdir);
    if (!mtx_is_executable(cand)) return false;
    snprintf(out, cap, "%s", cand);
    return true;
}

void gui_mediamtx_set_binary_path(const char *path)
{
    if (path && path[0]) snprintf(s_mediamtx_override, sizeof(s_mediamtx_override), "%s", path);
    else                 s_mediamtx_override[0] = '\0';
    mtx_bin.probed = false;
}

static bool mtx_resolve(char *out, size_t cap)
{
    if (mtx_is_executable(s_mediamtx_override)) {
        snprintf(out, cap, "%s", s_mediamtx_override);
        return true;
    }
    const char *env = getenv("MISRC_MEDIAMTX");
    if (mtx_is_executable(env)) { snprintf(out, cap, "%s", env); return true; }
    if (mtx_find_beside_self(out, cap)) return true;
    if (mtx_find_in_path(out, cap)) return true;
    const char *fallbacks[] = { "/usr/local/bin/mediamtx", "/usr/bin/mediamtx" };
    for (size_t i = 0; i < sizeof(fallbacks) / sizeof(fallbacks[0]); i++) {
        if (mtx_is_executable(fallbacks[i])) { snprintf(out, cap, "%s", fallbacks[i]); return true; }
    }
    return false;
}

bool gui_mediamtx_probe(void)
{
    if (mtx_bin.probed) return mtx_bin.found;
    mtx_bin.probed = true;
    mtx_bin.path[0] = '\0';
    mtx_bin.version[0] = '\0';
    mtx_bin.found = mtx_resolve(mtx_bin.path, sizeof(mtx_bin.path));
    if (!mtx_bin.found) return false;

    char cmd[600];
    snprintf(cmd, sizeof(cmd), "\"%s\" --version 2>/dev/null", mtx_bin.path);
    FILE *f = popen(cmd, "r");
    if (f) {
        if (fgets(mtx_bin.version, sizeof(mtx_bin.version), f)) {
            mtx_bin.version[strcspn(mtx_bin.version, "\r\n")] = '\0';
        }
        pclose(f);
    }
    return true;
}

const char *gui_mediamtx_binary_path(void) { return mtx_bin.found ? mtx_bin.path : ""; }
const char *gui_mediamtx_version(void)     { return mtx_bin.version; }

/* The directory must be ours and private before anything is written into it.
 *
 * mkdir() tolerating EEXIST is not the same as owning what already exists, and
 * the last fallback below is /tmp, which is world-writable: another user can
 * pre-create /tmp/misrc-gui and then read -- or replace -- everything we put
 * there. Once the config carries a stream password that stops being untidy and
 * starts being a leak, so it is checked here rather than assumed.
 *
 * lstat rather than stat: a symlink is not a directory we own, and following it
 * is exactly the trick being guarded against. */
static bool mtx_dir_is_private(const char *path)
{
    struct stat st;
    if (lstat(path, &st) != 0) return false;
    if (!S_ISDIR(st.st_mode)) { errno = ENOTDIR; return false; }
    if (st.st_uid != geteuid()) { errno = EPERM;  return false; }
    if (st.st_mode & (S_IRWXG | S_IRWXO)) {
        /* Ours, but looser than it should be. Tighten rather than refuse -- an
         * older build, or a stray umask, should not wedge the feature. */
        if (chmod(path, 0700) != 0) return false;
    }
    return true;
}

/* $XDG_RUNTIME_DIR is cleaned on reboot and is per-user; $TMPDIR is the
 * fallback for a session that has none. */
static bool mtx_config_dir(char *out, size_t cap)
{
    const char *base = getenv("XDG_RUNTIME_DIR");
    if (!base || !base[0]) base = getenv("TMPDIR");
    if (!base || !base[0]) base = "/tmp";
    snprintf(out, cap, "%s/misrc-gui", base);
    if (mkdir(out, 0700) != 0 && errno != EEXIST) return false;
    return mtx_dir_is_private(out);
}

static int mtx_write_config(const gui_mediamtx_config_t *cfg, char *err, size_t err_cap)
{
    /* Deliberately much smaller than config_path, so appending the filename
     * cannot truncate -- a half-written path would point somewhere real but
     * wrong. */
    char dir[256];
    if (!mtx_config_dir(dir, sizeof(dir))) {
        snprintf(err, err_cap, "cannot create runtime dir for the mediamtx config: %s",
                 strerror(errno));
        return -1;
    }
    snprintf(mtx.config_path, sizeof(mtx.config_path), "%s/mediamtx.yml", dir);

    char body[8192];
    mtx.metrics_port = cfg->metrics;

    int n = gui_mediamtx_render_config(cfg, body, sizeof(body));
    if (n < 0) {
        snprintf(err, err_cap, "mediamtx config did not fit its buffer");
        return -1;
    }
    /* 0600 at creation rather than after the fact, so there is no window in
     * which the file exists and is readable. O_NOFOLLOW because the path may sit
     * under /tmp on a session with no XDG_RUNTIME_DIR, where a symlink planted
     * at our filename would redirect the write somewhere we can reach but did
     * not intend. */
    int fd = open(mtx.config_path, O_WRONLY | O_CREAT | O_TRUNC | O_NOFOLLOW,
                  S_IRUSR | S_IWUSR);
    if (fd < 0) {
        snprintf(err, err_cap, "cannot write %s: %s", mtx.config_path, strerror(errno));
        return -1;
    }
    /* O_CREAT leaves an existing file's mode alone, so a config written by an
     * older build stays 0644 unless this is said explicitly. */
    if (fchmod(fd, S_IRUSR | S_IWUSR) != 0) {
        snprintf(err, err_cap, "cannot restrict %s: %s", mtx.config_path, strerror(errno));
        close(fd);
        return -1;
    }
    FILE *f = fdopen(fd, "w");
    if (!f) {
        snprintf(err, err_cap, "cannot write %s: %s", mtx.config_path, strerror(errno));
        close(fd);
        return -1;
    }
    size_t wrote = fwrite(body, 1, (size_t)n, f);
    if (fclose(f) != 0 || wrote != (size_t)n) {
        snprintf(err, err_cap, "short write to %s", mtx.config_path);
        return -1;
    }
    return 0;
}

int gui_mediamtx_start(const gui_mediamtx_config_t *cfg, char *err, size_t err_cap)
{
    if (err && err_cap) err[0] = '\0';
    if (cfg == NULL) {
        if (err) snprintf(err, err_cap, "no mediamtx config supplied");
        return -1;
    }
    /* Idempotent, with one exception. mediamtx is deliberately left running
     * across streams -- restarting it per stream would drop every viewer that
     * was reconnecting -- but the credential lives in its config file, which is
     * only written at startup. So a changed password is the one thing worth a
     * restart: without this the panel would show a new password that the server
     * was not actually enforcing, which is worse than having no password at all.
     * Nothing is watching a stream that has stopped, so nobody is dropped. */
    if (mtx.running) {
        if (strcmp(mtx.read_password, cfg->read_password) == 0) return 0;
        gui_mediamtx_stop();
    }

    if (!gui_mediamtx_probe()) {
        if (err) snprintf(err, err_cap,
                          "mediamtx not found; install it or set its path in settings");
        return -1;
    }
    if (mtx_write_config(cfg, err, err_cap) != 0) return -1;

    char *argv[] = { (char *)mtx_bin.path, mtx.config_path, NULL };
    pid_t pid = 0;
    int rc = posix_spawn(&pid, mtx_bin.path, NULL, NULL, argv, environ);
    if (rc != 0) {
        if (err) snprintf(err, err_cap, "cannot spawn mediamtx: %s", strerror(rc));
        return -1;
    }

    /* A mediamtx that cannot bind exits at once, and capture-node's answer is to
     * sleep and then check. We cannot: this runs on the render thread, and half
     * a second of sleeping there is a visibly frozen window. Record when to look
     * instead, and let gui_mediamtx_poll() -- already called once a frame -- do
     * the looking. */
    /* Same posture as the publisher: serving viewers must never come at the
     * expense of getting RF onto disk. */
    if (setpriority(PRIO_PROCESS, (id_t)pid, MTX_CHILD_NICE) != 0) {
        /* Not worth refusing to stream over. */
    }

    snprintf(mtx.read_password, sizeof(mtx.read_password), "%s", cfg->read_password);
    mtx.child_pid = (int)pid;
    mtx.running = true;
    mtx.err_text[0] = '\0';
    mtx.verify_at = mtx_now() + 0.5;
    return 0;
}

void gui_mediamtx_stop(void)
{
    mtx.verify_at = 0.0;
    if (!mtx.running || mtx.child_pid <= 0) {
        mtx.running = false;
        mtx.child_pid = 0;
        return;
    }
    pid_t pid = (pid_t)mtx.child_pid;

    kill(pid, SIGTERM);
    double deadline = mtx_now() + MTX_TERM_GRACE_S;
    while (mtx_now() < deadline) {
        if (waitpid(pid, NULL, WNOHANG) == pid) {
            mtx.running = false;
            mtx.child_pid = 0;
            return;
        }
        mtx_sleep(0.05);
    }
    kill(pid, SIGKILL);
    deadline = mtx_now() + MTX_KILL_GRACE_S;
    while (mtx_now() < deadline) {
        if (waitpid(pid, NULL, WNOHANG) == pid) break;
        mtx_sleep(0.05);
    }
    mtx.running = false;
    mtx.child_pid = 0;
}

void gui_mediamtx_shutdown(void) { gui_mediamtx_stop(); }

/* Pulls paths_inbound_bytes for our path out of a Prometheus text dump.
 * Returns false when the path is not present -- which is normal before the
 * publisher connects. */
static bool met_parse_bytes(const char *body, uint64_t *out)
{
    /* Newer mediamtx emits paths_inbound_bytes; paths_bytes_received is the
     * older spelling of the same counter and both appear in 1.19. */
    static const char *const keys[] = { "paths_inbound_bytes{", "paths_bytes_received{" };
    for (size_t k = 0; k < sizeof(keys) / sizeof(keys[0]); k++) {
        for (const char *p = strstr(body, keys[k]); p; p = strstr(p + 1, keys[k])) {
            const char *eol = strchr(p, '\n');
            if (!eol) eol = p + strlen(p);
            /* Only our path. Any other would be someone else's stream. */
            const char *name = strstr(p, "name=\"misrc-preview\"");
            if (!name || name > eol) continue;
            const char *sp = NULL;
            for (const char *q = eol - 1; q > p; q--) {
                if (*q == ' ') { sp = q + 1; break; }
            }
            if (!sp) continue;
            char *end = NULL;
            unsigned long long v = strtoull(sp, &end, 10);
            if (end && end != sp) { *out = (uint64_t)v; return true; }
        }
    }
    return false;
}

static void met_reset(void)
{
    if (met.fd >= 0) close(met.fd);
    met.fd = -1;
    met.phase = MET_IDLE;
    met.len = 0;
    met.req_sent = 0;
}

/* Forgets the rate but keeps the connection machinery tidy. Called when the
 * server stops, so a stale number cannot linger next to a dead stream. */
static void met_forget(void)
{
    met_reset();
    met.last_at = 0.0;
    met.last_bytes = 0;
    met.kbps = 0;
    met.next_at = 0.0;
}

static void met_finish(void)
{
    uint64_t bytes = 0;
    if (met.len && met_parse_bytes(met.buf, &bytes)) {
        double now = mtx_now();
        if (met.last_at != 0.0 && now > met.last_at && bytes >= met.last_bytes) {
            double secs = now - met.last_at;
            met.kbps = (uint32_t)(((double)(bytes - met.last_bytes) * 8.0) / secs / 1000.0);
        }
        met.last_bytes = bytes;
        met.last_at = now;
    }
    met_reset();
    met.next_at = mtx_now() + MTX_METRICS_PERIOD_S;
}

static void met_step(void)
{
    if (!mtx.running || mtx.metrics_port == 0) { met_forget(); return; }

    double now = mtx_now();

    if (met.fd < 0) {
        if (now < met.next_at) return;
        int fd = socket(AF_INET, SOCK_STREAM | SOCK_NONBLOCK | SOCK_CLOEXEC, 0);
        if (fd < 0) { met.next_at = now + MTX_METRICS_PERIOD_S; return; }
        struct sockaddr_in sa;
        memset(&sa, 0, sizeof(sa));
        sa.sin_family = AF_INET;
        sa.sin_port = htons(mtx.metrics_port);
        sa.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
        int rc = connect(fd, (struct sockaddr *)&sa, sizeof(sa));
        if (rc != 0 && errno != EINPROGRESS) {
            close(fd);
            met.next_at = now + MTX_METRICS_PERIOD_S;
            return;
        }
        met.fd = fd;
        met.phase = MET_CONNECTING;
        met.started_at = now;
        met.len = 0;
        met.req_sent = 0;
        met.req_len = (size_t)snprintf(met.req, sizeof(met.req),
            "GET /metrics HTTP/1.0\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n");
        return;
    }

    /* A request that never completes must not wedge the sampler. */
    if (now - met.started_at > MTX_METRICS_TIMEOUT_S) {
        met_reset();
        met.next_at = now + MTX_METRICS_PERIOD_S;
        return;
    }

    if (met.phase == MET_CONNECTING) {
        int err = 0;
        socklen_t elen = sizeof(err);
        if (getsockopt(met.fd, SOL_SOCKET, SO_ERROR, &err, &elen) != 0) { met_reset(); return; }
        if (err == EINPROGRESS) return;         /* still connecting */
        if (err != 0) {
            met_reset();
            met.next_at = now + MTX_METRICS_PERIOD_S;
            return;
        }
        met.phase = MET_SENDING;
    }

    if (met.phase == MET_SENDING) {
        ssize_t n = send(met.fd, met.req + met.req_sent, met.req_len - met.req_sent,
                         MSG_NOSIGNAL);
        if (n < 0) {
            if (errno == EAGAIN || errno == EWOULDBLOCK) return;
            met_reset();
            met.next_at = now + MTX_METRICS_PERIOD_S;
            return;
        }
        met.req_sent += (size_t)n;
        if (met.req_sent < met.req_len) return;
        met.phase = MET_READING;
    }

    if (met.phase == MET_READING) {
        for (;;) {
            if (met.len + 1 >= sizeof(met.buf)) { met_finish(); return; }
            ssize_t n = recv(met.fd, met.buf + met.len, sizeof(met.buf) - met.len - 1, 0);
            if (n > 0) { met.len += (size_t)n; continue; }
            if (n == 0) { met.buf[met.len] = '\0'; met_finish(); return; }
            if (errno == EAGAIN || errno == EWOULDBLOCK) return;   /* more later */
            met_reset();
            met.next_at = now + MTX_METRICS_PERIOD_S;
            return;
        }
    }
}

uint32_t gui_mediamtx_stream_kbps(void) { return met.kbps; }
const char *gui_mediamtx_read_password(void)
{
    return mtx.running ? mtx.read_password : "";
}

void gui_mediamtx_poll(void)
{
    met_step();

    if (!mtx.running || mtx.child_pid <= 0) return;
    int wstatus = 0;
    pid_t r = waitpid((pid_t)mtx.child_pid, &wstatus, WNOHANG);
    if (r != (pid_t)mtx.child_pid) {
        /* Survived its first half second, so it bound its ports. */
        if (mtx.verify_at != 0.0 && mtx_now() > mtx.verify_at) mtx.verify_at = 0.0;
        return;
    }

    /* Died inside the startup window: almost always a port it could not bind,
     * which is the one failure worth naming precisely. */
    if (mtx.verify_at != 0.0) {
        /* The config path is already in the status struct; repeating it here
         * would not fit err_text and the truncation is a build error. */
        snprintf(mtx.err_text, sizeof(mtx.err_text),
                 "mediamtx exited at startup - a port it needs is already bound");
        mtx.verify_at = 0.0;
        mtx.running = false;
        mtx.child_pid = 0;
        return;
    }

    /* capture-node has no equivalent of this: there, a dead mediamtx is simply
     * gone until the daemon restarts, with nothing said. */
    if (WIFEXITED(wstatus)) {
        snprintf(mtx.err_text, sizeof(mtx.err_text),
                 "mediamtx exited with status %d", WEXITSTATUS(wstatus));
    } else if (WIFSIGNALED(wstatus)) {
        snprintf(mtx.err_text, sizeof(mtx.err_text),
                 "mediamtx killed by signal %d (%s)",
                 WTERMSIG(wstatus), strsignal(WTERMSIG(wstatus)));
    } else {
        snprintf(mtx.err_text, sizeof(mtx.err_text), "mediamtx is no longer running");
    }
    mtx.running = false;
    mtx.child_pid = 0;
}

gui_mediamtx_status_t gui_mediamtx_get_status(void)
{
    gui_mediamtx_status_t st = {0};
    st.running = mtx.running;
    st.available = mtx_bin.found;
    st.child_pid = mtx.child_pid;
    snprintf(st.err_text, sizeof(st.err_text), "%s", mtx.err_text);
    snprintf(st.binary_path, sizeof(st.binary_path), "%s", mtx_bin.found ? mtx_bin.path : "");
    snprintf(st.config_path, sizeof(st.config_path), "%s", mtx.config_path);
    return st;
}

bool gui_mediamtx_is_running(void) { return mtx.running; }

/* ---- headless harness ---------------------------------------------------- */

/* Bind-test rather than parsing `ss`: a port we can bind is a port nothing
 * holds, which is exactly the question, and it needs no external tool. */
static bool mtx_port_is_bound(uint16_t port, int socktype)
{
    int fd = socket(AF_INET, socktype, 0);
    if (fd < 0) return false;
    struct sockaddr_in addr = {0};
    addr.sin_family = AF_INET;
    addr.sin_port = htons(port);
    addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    /* Deliberately no SO_REUSEADDR: we want "is anyone holding this". */
    bool in_use = (bind(fd, (struct sockaddr *)&addr, sizeof(addr)) != 0) && (errno == EADDRINUSE);
    close(fd);
    return in_use;
}

static int mtx_expect(bool ok, const char *what)
{
    if (!ok) {
        fprintf(stderr, "ASSERTION FAILED: %s\n", what);
        return 1;
    }
    printf("  ok: %s\n", what);
    return 0;
}

int gui_mediamtx_test_main(int seconds)
{
    if (seconds <= 0) seconds = 2;
    gui_mediamtx_config_t cfg = gui_mediamtx_default_config();

    if (!gui_mediamtx_probe()) {
        fprintf(stderr, "mediamtx not found on this host; nothing to test\n");
        return 2;
    }
    printf("mediamtx: %s (%s)\n", gui_mediamtx_binary_path(), gui_mediamtx_version());

    /* capture-node's ports, sampled before we touch anything. The assertion is
     * that starting our server changes none of them. */
    const uint16_t cn_tcp[] = { 8554, 18554, 28554 };
    bool cn_before[3];
    for (int i = 0; i < 3; i++) cn_before[i] = mtx_port_is_bound(cn_tcp[i], SOCK_STREAM);

    for (int i = 0; i < 3; i++) {
        if (mtx_port_is_bound(cfg.rtsp, SOCK_STREAM)) {
            fprintf(stderr, "port %u is already bound before we start\n", cfg.rtsp);
            return 1;
        }
        break;
    }

    char err[256];
    if (gui_mediamtx_start(&cfg, err, sizeof(err)) != 0) {
        fprintf(stderr, "start failed: %s\n", err);
        return 1;
    }
    printf("started pid %d, config %s\n",
           gui_mediamtx_get_status().child_pid, gui_mediamtx_get_status().config_path);

    /* Give every listener time to come up before asserting on them. */
    mtx_sleep(1.0);

    int bad = 0;
    bad |= mtx_expect(mtx_port_is_bound(cfg.rtsp, SOCK_STREAM), "rtsp port bound");
    bad |= mtx_expect(mtx_port_is_bound(cfg.hls, SOCK_STREAM), "hls port bound");
    bad |= mtx_expect(mtx_port_is_bound(cfg.webrtc_http, SOCK_STREAM), "webrtc http port bound");
    bad |= mtx_expect(mtx_port_is_bound(cfg.rtp, SOCK_DGRAM), "rtp port bound");
    bad |= mtx_expect(mtx_port_is_bound(cfg.rtcp, SOCK_DGRAM), "rtcp port bound");
    bad |= mtx_expect(mtx_port_is_bound(cfg.webrtc_ice, SOCK_DGRAM), "webrtc ice port bound");

    for (int i = 0; i < 3; i++) {
        char what[64];
        snprintf(what, sizeof(what), "capture-node port %u unchanged", cn_tcp[i]);
        bad |= mtx_expect(mtx_port_is_bound(cn_tcp[i], SOCK_STREAM) == cn_before[i], what);
    }

    /* Health poll must not declare a live server dead. */
    gui_mediamtx_poll();
    bad |= mtx_expect(gui_mediamtx_is_running(), "still running after poll");

    mtx_sleep((double)seconds);

    int pid = gui_mediamtx_get_status().child_pid;
    gui_mediamtx_stop();
    bad |= mtx_expect(!gui_mediamtx_is_running(), "stopped");
    bad |= mtx_expect(pid <= 0 || kill(pid, 0) != 0 || errno == ESRCH, "no child survives");

    mtx_sleep(0.3);
    bad |= mtx_expect(!mtx_port_is_bound(cfg.rtsp, SOCK_STREAM), "rtsp port released");
    bad |= mtx_expect(!mtx_port_is_bound(cfg.hls, SOCK_STREAM), "hls port released");
    bad |= mtx_expect(!mtx_port_is_bound(cfg.webrtc_http, SOCK_STREAM), "webrtc http port released");

    for (int i = 0; i < 3; i++) {
        char what[64];
        snprintf(what, sizeof(what), "capture-node port %u still unchanged", cn_tcp[i]);
        bad |= mtx_expect(mtx_port_is_bound(cn_tcp[i], SOCK_STREAM) == cn_before[i], what);
    }

    if (bad) {
        fprintf(stderr, "mediamtx test FAILED\n");
        return 1;
    }
    puts("mediamtx test passed");
    return 0;
}

#endif /* _WIN32 */
